<h4 class="news">
<img class="ico_news" src="img/ico_news.png" />Seminarul cu tema: "Instruire privind gestionarea riscurilor şi prevenirea delictelor în sectorul bancar"
</h4>
<div class="newscontent">
<p>În perioada 24-25 mai 2010, la Banca Naţională a Moldovei s-a desfăşurat un seminar de instruire a reprezentanţilor băncilor din Moldova privind gestionarea riscurilor şi prevenirea delictelor în sectorul bancar pe timp de criză. Întrunirea este organizată în comun cu Corporaţia Financiară Internaţională din cadrul Grupului Băncii Mondiale.</p>
<p>Guvernatorul Băncii Naţionale Dorin Drăguţanu a salutat preocuparea băncilor comerciale pentru gestionarea corectă a riscului de credit, însuşirea noilor tehnici şi experienţe aferente. "O gestiune eficientă a riscului de credit duce la diminuarea pierderilor, la stabilirea unei rate mai adecvate a dobânzii la credite, ceea ce contribuie la sporirea afacerii şi la stabilirea unui preţ corect şi pentru bancă, şi pentru clienţii acesteia", a spus Dorin Drăguţanu.</p>
<p>Şefa Misiunii Corporaţiei Financiare Internaţionale pentru Moldova şi România Ana Maria Mihăescu a apreciat interesul mediului bancar pentru acest eveniment, menţionând că Programul IFC pentru Moldova este focalizat prioritar pe sectorul financiar, dar se va extinde, de asemenea, în sectorul agricol şi cel de infrastructură. "Misiunea IFC este în Moldova din 1996, iar în ultimii doi ani prezenţa acesteia este mai simţită decât în anii trecuţi. Programul nostru este un răspuns pentru criză", a declarat Ana Maria Mihăescu.</p>
<p>Experţii Corporaţiei Financiare Internaţionale au vorbit despre instrumentele managementului riscului de credit pe plan internaţional, despre cele mai frecvente deficienţe în gestionarea riscului de credit, interpretarea MRC sub aspectul principiilor Comitetului BASEL. De asemenea, au pus în discuţie avantajele identificării timpurii a creditelor potenţial problematice, semnele de alertă ale problemelor ce ţin de portofoliul de credere, rolul şi responsabilităţile departamentelor responsabile de situaţia creditelor problematice.</p>
<p>Viceguvernatorul BNM Emma Tăbîrţă a menţionat în deschiderea seminarului că o componentă importantă a sistemului de gestiune a riscului de credit reprezintă informaţia adecvată obţinută în timp util, precum şi capacitatea de a o prelucra şi interpreta. "Riscurile urmează să fie acoperite în toată instituţia, prin colectarea şi procesarea informaţiei în timp real. Conducerea băncii trebuie să cunoască structura riscurilor şi nivelul fiecărui risc în parte caracteristic oricărui gen de activitate, precum şi importanţa obţinerii unei informaţii relevante", a comunicat Emma Tăbîrţă.</p>
<p>Banca Naţională a Moldovei a intensificat monitorizarea la distanţă a riscurilor aferente activităţii de creditare a băncilor, a informat directorul Departamentului reglementare şi supraveghere bancară Vladimir Ţurcanu.</p>
<p>De asemenea, printre alte acţiuni ale BNM în vederea minimizării riscurilor în bănci, trebuie menţionată şi solicitarea efectuării de către acestea a unui studiu diagnostic al situaţiei financiare conform metodologiei FMI. Banca Naţională a efectuat testări la stres în cazul fiecărei bănci, pe grupe de bănci, pe întreg sistemul bancar, vizând riscul de lichiditate, riscul de credit, riscul valutar, riscul ratei dobânzii şi combinarea diferitelor riscuri.</p>
</div>